apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bxj9d8hno-go 
  janus-idp.io/tekton: bxj9d8hno-go
  backstage.io/kubernetes-id: bxj9d8hno-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bxj9d8hno-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  