apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bxj9d8hno-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bxj9d8hno-go 
  name: bxj9d8hno-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bxj9d8hno-go 
